AWSTemplateFormatVersion: 2010-09-09
Resources:
  TasksAPIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-name
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
